# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric tblstyle = latex craction = 1
format A 10 0 0
format B 8 0 0
format C 6 2 0
format D 6 2 0
format E 12 2 0
format F 11 2 0
format G 6 0 0
format H 11 2 0
format I 13 1 0
fkey 3 = "Get \"!co -q -p test.sc\""
fkey 4 = "Get \"|co -q -p`rlog test.sc|grep locked|awk '{ print $2 }'` test.sc\""
leftstring A0 = "date of"
rightstring B0 = "mileage"
rightstring C0 = "added"
rightstring D0 = "after"
rightstring E0 = "consumption"
rightstring F0 = "unit price"
rightstring G0 = "price"
rightstring H0 = "total cost"
rightstring I0 = "comments"
leftstring A1 = "filling"
rightstring B1 = "(km)"
rightstring C1 = "(L)"
rightstring D1 = "(L)"
rightstring E1 = "(km/L)"
rightstring F1 = "(yen/L)"
rightstring G1 = "(yen)"
rightstring H1 = "(man yen)"
let A2 = @dts(2012,8,26)
fmt A2 "%F"
let B2 = 15121
let C2 = 27.33
let D2 = 34
let E2 = @avg(E3:E110)
let F2 = 134
let G2 = 3662
let H2 = G2/10000
let A3 = @dts(2012,9,2)
fmt A3 "%F"
let B3 = 15453
let C3 = 20.34
let D3 = 34
let E3 = (B3-B2)/C3
let F3 = 136
let G3 = 2766
let H3 = G3/10000+H2
let A4 = @dts(2012,9,13)
fmt A4 "%F"
let B4 = 16046
let C4 = 10
let D4 = 10
let E4 = (B5-B3)/(C5+C4)
let F4 = 147
let G4 = 1470
let H4 = G4/10000+H3
let A5 = @dts(2012,9,14)
fmt A5 "%F"
let B5 = 16106
let C5 = 25.8
let D5 = 34
let E5 = (B5-B3)/(C5+C4)
let F5 = 142
let G5 = 3664
let H5 = G5/10000+H4
let A6 = @dts(2012,10,7)
fmt A6 "%F"
let B6 = 16569
let C6 = 29.87
let D6 = 34
let E6 = (B6-B5)/C6
let F6 = 139
let G6 = 4152
let H6 = G6/10000+H5
let A7 = @dts(2012,10,14)
fmt A7 "%F"
let B7 = 16893
let C7 = 16.12
let D7 = 34
let E7 = (B7-B6)/C7
let F7 = 139
let G7 = 2241
let H7 = G7/10000+H6
let A8 = @dts(2012,10,25)
fmt A8 "%F"
let B8 = 17473
let C8 = 33.06
let D8 = 34
let E8 = (B8-B7)/C8
let F8 = 141
let G8 = 4461
let H8 = G8/10000+H7
let A9 = @dts(2012,11,3)
fmt A9 "%F"
let B9 = 17917
let C9 = 25.65
let D9 = 34
let E9 = (B9-B8)/C9
let F9 = 137
let G9 = 3514
let H9 = G9/10000+H8
let A10 = @dts(2012,11,10)
fmt A10 "%F"
let B10 = 18325
let C10 = 22.8
let D10 = 34
let E10 = (B10-B9)/C10
let F10 = 137
let G10 = 3124
let H10 = G10/10000+H9
let A11 = @dts(2012,11,18)
fmt A11 "%F"
let B11 = 18648
let C11 = 18.41
let D11 = 34
let E11 = (B11-B10)/C11
let F11 = 135
let G11 = 2486
let H11 = G11/10000+H10
rightstring I11 = "snow tires"
let A12 = @dts(2012,11,25)
fmt A12 "%F"
let B12 = 18905
let C12 = 15.2
let D12 = 34
let E12 = (B12-B11)/C12
let F12 = 136
let G12 = 2067
let H12 = G12/10000+H11
let A13 = @dts(2012,12,2)
fmt A13 "%F"
let B13 = 19305
let C13 = 23.77
let D13 = 34
let E13 = (B13-B12)/C13
let F13 = 138
let G13 = 3280
let H13 = G13/10000+H12
let A14 = @dts(2012,12,8)
fmt A14 "%F"
let B14 = 19648
let C14 = 20.99
let D14 = 34
let E14 = (B14-B13)/C14
let F14 = 140
let G14 = 2939
let H14 = G14/10000+H13
let A15 = @dts(2012,12,16)
fmt A15 "%F"
let B15 = 19991
let C15 = 23.07
let D15 = 34
let E15 = (B15-B14)/C15
let F15 = 140
let G15 = 3253
let H15 = G15/10000+H14
rightstring I15 = "4 wheel"
let A16 = @dts(2012,12,24)
fmt A16 "%F"
let B16 = 20373
let C16 = 22.94
let D16 = 34
let E16 = (B16-B15)/C16
let F16 = 138
let G16 = 3167
let H16 = G16/10000+H15
let A17 = @dts(2013,1,6)
fmt A17 "%F"
let B17 = 20854
let C17 = 31.95
let D17 = 34
let E17 = (B17-B16)/C17
let F17 = 141
let G17 = 4505
let H17 = G17/10000+H16
rightstring I17 = "4w,hw,4p"
let A18 = @dts(2013,1,17)
fmt A18 "%F"
let B18 = 21368
let C18 = 32.08
let D18 = 34
let E18 = (B18-B17)/C18
let F18 = 146
let G18 = 4684
let H18 = G18/10000+H17
rightstring I18 = "some snow"
let A19 = @dts(2013,1,26)
fmt A19 "%F"
let B19 = 21736
let C19 = 22.74
let D19 = 34
let E19 = (B19-B18)/C19
let F19 = 142
let G19 = 3230
let H19 = G19/10000+H18
rightstring I19 = "oil change"
let A20 = @dts(2013,2,3)
fmt A20 "%F"
let B20 = 22184
let C20 = 26.71
let D20 = 34
let E20 = (B20-B19)/C20
let F20 = 141
let G20 = 3766
let H20 = G20/10000+H19
rightstring I20 = "engine break"
let A21 = @dts(2013,2,10)
fmt A21 "%F"
let B21 = 22570
let C21 = 23.95
let D21 = 34
let E21 = (B21-B20)/C21
let F21 = 144
let G21 = 3449
let H21 = G21/10000+H20
let A22 = @dts(2013,2,17)
fmt A22 "%F"
let B22 = 22828
let C22 = 17.52
let D22 = 34
let E22 = (B22-B21)/C22
let F22 = 147
let G22 = 2575
let H22 = G22/10000+H21
rightstring I22 = "gas station"
let A23 = @dts(2013,2,23)
fmt A23 "%F"
let B23 = 23210
let C23 = 22.05
let D23 = 34
let E23 = (B23-B22)/C23
let F23 = 148
let G23 = 3263
let H23 = G23/10000+H22
rightstring I23 = "gas station"
let A24 = @dts(2013,3,3)
fmt A24 "%F"
let B24 = 23736
let C24 = 31.52
let D24 = 34
let E24 = (B24-B23)/C24
let F24 = 147
let G24 = 4633
let H24 = G24/10000+H23
let A25 = @dts(2013,3,10)
fmt A25 "%F"
let B25 = 24057
let C25 = 19.57
let D25 = 34
let E25 = (B25-B24)/C25
let F25 = 147
let G25 = 2877
let H25 = G25/10000+H24
let A26 = @dts(2013,3,16)
fmt A26 "%F"
let B26 = 24376
let C26 = 18.74
let D26 = 34
let E26 = (B26-B25)/C26
let F26 = 143
let G26 = 2680
let H26 = G26/10000+H25
rightstring I26 = "bleeding"
let A27 = @dts(2013,3,31)
fmt A27 "%F"
let B27 = 24697
let C27 = 18.14
let D27 = 34
let E27 = (B27-B26)/C27
let F27 = 146
let G27 = 2648
let H27 = G27/10000+H26
let A28 = @dts(2013,4,22)
fmt A28 "%F"
let B28 = 25094
let C28 = 24.42
let D28 = 34
let E28 = (B28-B27)/C28
let F28 = 147
let G28 = 3590
let H28 = G28/10000+H27
let A29 = @dts(2013,4,28)
fmt A29 "%F"
let B29 = 25421
let C29 = 18.27
let D29 = 34
let E29 = (B29-B28)/C29
let F29 = 145
let G29 = 2649
let H29 = G29/10000+H28
let A30 = @dts(2013,5,11)
fmt A30 "%F"
let B30 = 25923
let C30 = 27.69
let D30 = 34
let E30 = (B30-B29)/C30
let F30 = 144
let G30 = 3988
let H30 = G30/10000+H29
rightstring I30 = "speed up"
let A31 = @dts(2013,5,20)
fmt A31 "%F"
let B31 = 26380
let C31 = 24.92
let D31 = 34
let E31 = (B31-B30)/C31
let F31 = 144
let G31 = 3588
let H31 = G31/10000+H30
rightstring I31 = "oil change"
leftstring A33 = "# daily"
leftstring B33 = "mileage"
leftstring C33 = "[km]"
leftstring D33 = "..."
leftstring E33 = "..."
leftstring F33 = "..."
leftstring G33 = "..."
let H33 = (B31-B2)/((A31-A2)/24/3600)
leftstring A34 = "# daily"
leftstring B34 = "cost"
leftstring C34 = "of"
leftstring D34 = "fuel"
leftstring E34 = "[yen]"
leftstring F34 = "..."
leftstring G34 = "..."
let H34 = (H31-H2)/((A31-A2)/24/3600)*10000
fmt H34 "0"
goto H35 A0
