# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric tblstyle = latex craction = 1
format 5 = "%F"
format A 10 0 0
format B 8 0 0
format C 6 2 0
format D 6 2 0
format E 12 2 0
format F 11 2 0
format G 6 0 0
format H 11 2 0
format I 13 1 0
fkey 3 = "Get \"!co -q -p test.sc\""
fkey 4 = "Get \"|co -q -p`rlog test.sc|grep locked|awk '{ print $2 }'` test.sc\""
leftstring A0 = "date of"
rightstring B0 = "mileage"
rightstring C0 = "added"
rightstring D0 = "after"
rightstring E0 = "consumption"
rightstring F0 = "unit price"
rightstring G0 = "price"
rightstring H0 = "total cost"
rightstring I0 = "comments"
leftstring A1 = "filling"
rightstring B1 = "(km)"
rightstring C1 = "(L)"
rightstring D1 = "(L)"
rightstring E1 = "(km/L)"
rightstring F1 = "(yen/L)"
rightstring G1 = "(yen)"
rightstring H1 = "(man yen)"
let A2 = @dts(2012,8,26)
fmt A2 "%F"
let B2 = 15121
let C2 = 27.33
let D2 = 34
let E2 = @avg(E3:E126)
let F2 = 134
let G2 = 3662
let H2 = G2/10000
let A3 = @dts(2012,9,2)
fmt A3 "%F"
let B3 = 15453
let C3 = 20.34
let D3 = 34
let E3 = (B3-B2)/C3
let F3 = 136
let G3 = 2766
let H3 = G3/10000+H2
let A4 = @dts(2012,9,13)
fmt A4 "%F"
let B4 = 16046
let C4 = 10
let D4 = 10
let E4 = (B5-B3)/(C5+C4)
let F4 = 147
let G4 = 1470
let H4 = G4/10000+H3
let A5 = @dts(2012,9,14)
fmt A5 "%F"
let B5 = 16106
let C5 = 25.8
let D5 = 34
let E5 = (B5-B3)/(C5+C4)
let F5 = 142
let G5 = 3664
let H5 = G5/10000+H4
let A6 = @dts(2012,10,7)
fmt A6 "%F"
let B6 = 16569
let C6 = 29.87
let D6 = 34
let E6 = (B6-B5)/C6
let F6 = 139
let G6 = 4152
let H6 = G6/10000+H5
let A7 = @dts(2012,10,14)
fmt A7 "%F"
let B7 = 16893
let C7 = 16.12
let D7 = 34
let E7 = (B7-B6)/C7
let F7 = 139
let G7 = 2241
let H7 = G7/10000+H6
let A8 = @dts(2012,10,25)
fmt A8 "%F"
let B8 = 17473
let C8 = 33.06
let D8 = 34
let E8 = (B8-B7)/C8
let F8 = 141
let G8 = 4461
let H8 = G8/10000+H7
let A9 = @dts(2012,11,3)
fmt A9 "%F"
let B9 = 17917
let C9 = 25.65
let D9 = 34
let E9 = (B9-B8)/C9
let F9 = 137
let G9 = 3514
let H9 = G9/10000+H8
let A10 = @dts(2012,11,10)
fmt A10 "%F"
let B10 = 18325
let C10 = 22.8
let D10 = 34
let E10 = (B10-B9)/C10
let F10 = 137
let G10 = 3124
let H10 = G10/10000+H9
let A11 = @dts(2012,11,18)
fmt A11 "%F"
let B11 = 18648
let C11 = 18.41
let D11 = 34
let E11 = (B11-B10)/C11
let F11 = 135
let G11 = 2486
let H11 = G11/10000+H10
rightstring I11 = "snow tires"
let A12 = @dts(2012,11,25)
fmt A12 "%F"
let B12 = 18905
let C12 = 15.2
let D12 = 34
let E12 = (B12-B11)/C12
let F12 = 136
let G12 = 2067
let H12 = G12/10000+H11
let A13 = @dts(2012,12,2)
fmt A13 "%F"
let B13 = 19305
let C13 = 23.77
let D13 = 34
let E13 = (B13-B12)/C13
let F13 = 138
let G13 = 3280
let H13 = G13/10000+H12
let A14 = @dts(2012,12,8)
fmt A14 "%F"
let B14 = 19648
let C14 = 20.99
let D14 = 34
let E14 = (B14-B13)/C14
let F14 = 140
let G14 = 2939
let H14 = G14/10000+H13
let A15 = @dts(2012,12,16)
fmt A15 "%F"
let B15 = 19991
let C15 = 23.07
let D15 = 34
let E15 = (B15-B14)/C15
let F15 = 140
let G15 = 3253
let H15 = G15/10000+H14
rightstring I15 = "4 wheel"
let A16 = @dts(2012,12,24)
fmt A16 "%F"
let B16 = 20373
let C16 = 22.94
let D16 = 34
let E16 = (B16-B15)/C16
let F16 = 138
let G16 = 3167
let H16 = G16/10000+H15
let A17 = @dts(2013,1,6)
fmt A17 "%F"
let B17 = 20854
let C17 = 31.95
let D17 = 34
let E17 = (B17-B16)/C17
let F17 = 141
let G17 = 4505
let H17 = G17/10000+H16
rightstring I17 = "4w,hw,4p"
let A18 = @dts(2013,1,17)
fmt A18 "%F"
let B18 = 21368
let C18 = 32.08
let D18 = 34
let E18 = (B18-B17)/C18
let F18 = 146
let G18 = 4684
let H18 = G18/10000+H17
rightstring I18 = "some snow"
let A19 = @dts(2013,1,26)
fmt A19 "%F"
let B19 = 21736
let C19 = 22.74
let D19 = 34
let E19 = (B19-B18)/C19
let F19 = 142
let G19 = 3230
let H19 = G19/10000+H18
rightstring I19 = "oil change"
let A20 = @dts(2013,2,3)
fmt A20 "%F"
let B20 = 22184
let C20 = 26.71
let D20 = 34
let E20 = (B20-B19)/C20
let F20 = 141
let G20 = 3766
let H20 = G20/10000+H19
rightstring I20 = "engine break"
let A21 = @dts(2013,2,10)
fmt A21 "%F"
let B21 = 22570
let C21 = 23.95
let D21 = 34
let E21 = (B21-B20)/C21
let F21 = 144
let G21 = 3449
let H21 = G21/10000+H20
let A22 = @dts(2013,2,17)
fmt A22 "%F"
let B22 = 22828
let C22 = 17.52
let D22 = 34
let E22 = (B22-B21)/C22
let F22 = 147
let G22 = 2575
let H22 = G22/10000+H21
rightstring I22 = "gas station"
let A23 = @dts(2013,2,23)
fmt A23 "%F"
let B23 = 23210
let C23 = 22.05
let D23 = 34
let E23 = (B23-B22)/C23
let F23 = 148
let G23 = 3263
let H23 = G23/10000+H22
rightstring I23 = "gas station"
let A24 = @dts(2013,3,3)
fmt A24 "%F"
let B24 = 23736
let C24 = 31.52
let D24 = 34
let E24 = (B24-B23)/C24
let F24 = 147
let G24 = 4633
let H24 = G24/10000+H23
let A25 = @dts(2013,3,10)
fmt A25 "%F"
let B25 = 24057
let C25 = 19.57
let D25 = 34
let E25 = (B25-B24)/C25
let F25 = 147
let G25 = 2877
let H25 = G25/10000+H24
let A26 = @dts(2013,3,16)
fmt A26 "%F"
let B26 = 24376
let C26 = 18.74
let D26 = 34
let E26 = (B26-B25)/C26
let F26 = 143
let G26 = 2680
let H26 = G26/10000+H25
rightstring I26 = "bleeding"
let A27 = @dts(2013,3,31)
fmt A27 "%F"
let B27 = 24697
let C27 = 18.14
let D27 = 34
let E27 = (B27-B26)/C27
let F27 = 146
let G27 = 2648
let H27 = G27/10000+H26
let A28 = @dts(2013,4,22)
fmt A28 "%F"
let B28 = 25094
let C28 = 24.42
let D28 = 34
let E28 = (B28-B27)/C28
let F28 = 147
let G28 = 3590
let H28 = G28/10000+H27
let A29 = @dts(2013,4,28)
fmt A29 "%F"
let B29 = 25421
let C29 = 18.27
let D29 = 34
let E29 = (B29-B28)/C29
let F29 = 145
let G29 = 2649
let H29 = G29/10000+H28
let A30 = @dts(2013,5,11)
fmt A30 "%F"
let B30 = 25923
let C30 = 27.69
let D30 = 34
let E30 = (B30-B29)/C30
let F30 = 144
let G30 = 3988
let H30 = G30/10000+H29
rightstring I30 = "speed up"
let A31 = @dts(2013,5,20)
fmt A31 "%F"
let B31 = 26380
let C31 = 24.92
let D31 = 34
let E31 = (B31-B30)/C31
let F31 = 144
let G31 = 3588
let H31 = G31/10000+H30
rightstring I31 = "oil change"
let A32 = @dts(2013,5,29)
fmt A32 "%F"
let B32 = 26910
let C32 = 28.61
let D32 = 34
let E32 = (B32-B31)/C32
let F32 = 143
let G32 = 4091
let H32 = G32/10000+H31
let A33 = @dts(2013,6,6)
fmt A33 "%F"
let B33 = 27349
let C33 = 23.92
let D33 = 34
let E33 = (B33-B32)/C33
let F33 = 141
let G33 = 3373
let H33 = G33/10000+H32
let A34 = @dts(2013,6,16)
fmt A34 "%F"
let B34 = 27895
let C34 = 29.46
let D34 = 34
let E34 = (B34-B33)/C34
let F34 = 143
let G34 = 4213
let H34 = G34/10000+H33
let A35 = @dts(2013,6,22)
fmt A35 "%F"
let B35 = 28276
let C35 = 21.35
let D35 = 34
let E35 = (B35-B34)/C35
let F35 = 143
let G35 = 3053
let H35 = G35/10000+H34
let A36 = @dts(2013,6,30)
fmt A36 "%F"
let B36 = 28689
let C36 = 22.4
let D36 = 34
let E36 = (B36-B35)/C36
let F36 = 144
let G36 = 3226
let H36 = G36/10000+H35
let A37 = @dts(2013,7,18)
fmt A37 "%F"
let B37 = 29213
let C37 = 28.15
let D37 = 34
let E37 = (B37-B36)/C37
let F37 = 150
let G37 = 4251
let H37 = G37/10000+H36
let A38 = @dts(2013,7,27)
fmt A38 "%F"
let B38 = 29795
let C38 = 32.47
let D38 = 34
let E38 = (B38-B37)/C38
let F38 = 149
let G38 = 4839
let H38 = G38/10000+H37
let A39 = @dts(2013,8,6)
fmt A39 "%F"
let B39 = 30359
let C39 = 29.21
let D39 = 34
let E39 = (B39-B38)/C39
let F39 = 152
let G39 = 4440
let H39 = G39/10000+H38
let A40 = @dts(2013,8,21)
fmt A40 "%F"
let B40 = 30904
let C40 = 30.29
let D40 = 34
let E40 = (B40-B39)/C40
let F40 = 151
let G40 = 4574
let H40 = G40/10000+H39
rightstring I40 = "summer tires"
let A41 = @dts(2013,9,1)
fmt A41 "%F"
let B41 = 31362
let C41 = 25.1
let D41 = 34
let E41 = (B41-B40)/C41
let F41 = 151
let G41 = 3790
let H41 = G41/10000+H40
let A42 = @dts(2013,9,13)
fmt A42 "%F"
let B42 = 31952
let C42 = 29.19
let D42 = 34
let E42 = (B42-B41)/C42
let F42 = 153
let G42 = 4466
let H42 = G42/10000+H41
let A43 = @dts(2013,9,28)
fmt A43 "%F"
let B43 = 32530
let C43 = 31.37
let D43 = 34
let E43 = (B43-B42)/C43
let F43 = 150
let G43 = 4706
let H43 = G43/10000+H42
let A44 = @dts(2013,10,9)
fmt A44 "%F"
let B44 = 33082
let C44 = 29.94
let D44 = 34
let E44 = (B44-B43)/C44
let F44 = 147
let G44 = 4401
let H44 = G44/10000+H43
let A45 = @dts(2013,10,20)
fmt A45 "%F"
let B45 = 33660
let C45 = 31.19
let D45 = 34
let E45 = (B45-B44)/C45
let F45 = 149
let G45 = 4648
let H45 = G45/10000+H44
let A46 = @dts(2013,10,30)
fmt A46 "%F"
let B46 = 34226
let C46 = 31.33
let D46 = 34
let E46 = (B46-B45)/C46
let F46 = 151
let G46 = 4731
let H46 = G46/10000+H45
let A47 = @dts(2013,11,8)
fmt A47 "%F"
let B47 = 34681
let C47 = 25.39
let D47 = 34
let E47 = (B47-B46)/C47
let F47 = 147
let G47 = 3732
let H47 = G47/10000+H46
leftstring A49 = "# daily"
leftstring B49 = "mileage"
leftstring C49 = "[km]"
leftstring D49 = "..."
leftstring E49 = "..."
leftstring F49 = "..."
leftstring G49 = "..."
let H49 = (B47-B2)/((A47-A2)/24/3600)
leftstring A50 = "# daily"
leftstring B50 = "cost"
leftstring C50 = "of"
leftstring D50 = "fuel"
leftstring E50 = "[yen]"
leftstring F50 = "..."
leftstring G50 = "..."
let H50 = (H47-H2)/((A47-A2)/24/3600)*10000
fmt H50 "0"
goto H49 A0
